In [15]:
import numpy as np
X = np.array(([2,9], [4,6], [1,4]), dtype=float)
Y = np.array(([89],[96],[83]), dtype=float)
X=X/np.amax(X,axis=0)
actual_output=Y/100

print(X)
print(actual_output)

[[0.5        1.        ]
 [1.         0.66666667]
 [0.25       0.44444444]]
[[0.89]
 [0.96]
 [0.83]]


In [16]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
    
def sigmoid_der(x):
    return x*(1-x)

In [28]:
epochs = 100
learning_rate = 1.5
input = 2
hidden = 3
output = 1

wh = np.random.uniform(low=-0.05, high=0.05, size=(input,hidden))
bh = np.random.uniform(low=-0.05, high=0.05, size=(1,hidden))

wo = np.random.uniform(low=-0.05, high=0.05, size=(hidden,output))
bo = np.random.uniform(low=-0.05, high=0.05, size=(1,output))

for i in range(epochs):
    
    net_h = np.dot(X,wh) + bh
    sigma_h = sigmoid(net_h)

    net_o = np.dot(sigma_h,wo) + bo
    sigma_o = sigmoid(net_o)

    eo = actual_output - sigma_o
    outgrad = sigmoid_der(sigma_o)
    d_output = eo*outgrad
    
    eh = d_output.dot(wo.T)
    hiddengrad = sigmoid_der(sigma_h)
    d_hidden = eh*hiddengrad
    
    wh+=X.T.dot(d_hidden)*learning_rate
    wo+= sigma_h.T.dot(d_output)*learning_rate
    

In [29]:
sum_error = 0

for j in range(len(actual_output)):
    print(sigma_o[j], actual_output[j])
    sum_error+=((sigma_o[j]-actual_output[j])**2)
    
sum_error = sum_error/len(actual_output)

print(sum_error*100)

[0.89745823] [0.89]
[0.90369626] [0.96]
[0.87864795] [0.83]
[0.18641199]


In [30]:
print("Input: \n" + str(X))
print("Actual Output: \n" + str(actual_output))
print("Predicted Output: \n" ,sigma_o)

Input: 
[[0.5        1.        ]
 [1.         0.66666667]
 [0.25       0.44444444]]
Actual Output: 
[[0.89]
 [0.96]
 [0.83]]
Predicted Output: 
 [[0.89745823]
 [0.90369626]
 [0.87864795]]
